=== TimSeredinski/Task03/taskWithXMLAndXSD/src/main/resources/menuXSD.xsd
<?xml version="1.0" encoding="utf-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.epam.tr.by/menu"
        xmlns:tns="http://www.epam.tr.by/menu"
        elementFormDefault="qualified">
    <element name="menu">
        <complexType>
            <sequence>
                <element name="Cold-Dish" type="tns:Cold-Dish" maxOccurs="unbounded"/>
                <element name="Warm-Dish" type="tns:Warm-Dish" maxOccurs="unbounded"/>
                <element name="Breakfast" type="tns:Breakfast" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Cold-Dish">
        <sequence>
            <element name="img" type="string"/>
            <element name="name" type="string"/>
            <element name="description" type="string"/>
            <element name="extra_desc" type="tns:extra_desc" minOccurs="0"/>
            <element name="portion" type="string"/>
            <element name="price" type="double"/>
        </sequence>
        <attribute name="id" use="required"/>
    </complexType>
    <complexType name="Warm-Dish">
        <sequence>
            <element name="img"/>
            <element name="name" type="string"/>
            <element name="description" type="string"/>
            <element name="extra_desc" type="tns:extra_desc" minOccurs="0"/>
            <element name="portion" type="string"/>
            <element name="price" type="double"/>
        </sequence>
        <attribute name="id" use="required"/>
    </complexType>
    <complexType name="Breakfast">
        <sequence>
            <element name="img"/>
            <element name="name" type="string"/>
            <element name="description" type="string"/>
            <element name="extra_desc" type="tns:extra_desc" minOccurs="0"/>
            <element name="portion" type="string"/>
            <element name="price" type="double"/>
        </sequence>
        <attribute name="id" use="required"/>
    </complexType>


    <complexType name="extra_desc">
        <sequence>
            <element name="addition" minOccurs="0" maxOccurs="unbounded">
                <complexType>
                    <sequence>
                        <element name="addition_desc" type="string"/>
                        <element name="addition_portion" type="string"/>
                        <element name="price" type="int"/>
                    </sequence>
                </complexType>
            </element>
        </sequence>
    </complexType>
</schema>

=== TimSeredinski/Task03/taskWithXMLAndXSD/src/main/resources/menu.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<menu   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.epam.tr.by/menu"
        xsi:schemaLocation="http://www.epam.tr.by/menu menuXSD.xsd">
    <Cold-Dish id="1">
        <img>images/dishes/dish1_1.jpg</img>
        <name>Ассорти рыбное</name>
        <description>Слабосоленая форель, семга</description>
        <extra_desc>
            <addition>
                <addition_desc>фирменный соус</addition_desc>
                <addition_portion>20</addition_portion>
                <price>15</price>
            </addition>
        </extra_desc>
        <portion>110</portion>
        <price>80</price>
    </Cold-Dish>
    <Cold-Dish id="2">
        <img>images/dishes/dish1_2.jpg</img>
        <name>Тарталетки с красной икрой</name>
        <description>Тарталетки с красной икрой</description>
        <portion>60/50</portion>
        <price>130</price>
    </Cold-Dish>
    <Cold-Dish id="3">
        <img>images/dishes/dish1_3.jpg</img>
        <name>Закуска по-русски</name>
        <description>Кусочки атлантической сельди с отварным картофелем, луком, лимоном и зеленью</description>
        <portion>70/50/2/10</portion>
        <price>90</price>
    </Cold-Dish>
    <Cold-Dish id="4">
        <img>images/dishes/dish1_4.jpg</img>
        <name>Куриный рулет</name>
        <description>Куриный рулет собственного производства</description>
        <portion>100/5</portion>
        <price>120</price>
    </Cold-Dish>
    <Warm-Dish id="1">
        <img>images/dishes/dish2_1.jpg</img>
        <name>Лобио с шампиньонами</name>
        <description>Фасоль с шампиньонами и грецким орехом</description>
        <portion>150/5</portion>
        <price>105</price>
    </Warm-Dish>
    <Warm-Dish id="2">
        <img>images/dishes/dish2_2.jpg</img>
        <name>Жульен</name>
        <description>с курицей/с грибами</description>
        <portion>120/1</portion>
        <price>114.5</price>
    </Warm-Dish>
    <Warm-Dish id="3">
        <img>images/dishes/dish2_3.jpg</img>
        <name>Ахтамар мясной</name>
        <description>Колбаса, ветчина, буженина, сыр, запеченые на мангале в лаваше</description>
        <portion>120</portion>
        <price>150</price>
    </Warm-Dish>
    <Warm-Dish id="4">
        <img>images/dishes/dish2_4.jpg</img>
        <name>Ахтамар с овощами</name>
        <description>Сыр, помидоры, зелень, запеченые на мангале в лаваше</description>
        <portion>150/5</portion>
        <price>105</price>
    </Warm-Dish>
    <Breakfast id="1">
        <img>images/dishes/dish3_1.jpg</img>
        <name>Глазунья</name>
        <description>2 яйца</description>
        <extra_desc>
            <addition>
                <addition_desc>ветчина</addition_desc>
                <addition_portion>20</addition_portion>
                <price>10</price>
            </addition>
            <addition>
                <addition_desc>сыр</addition_desc>
                <addition_portion>10</addition_portion>
                <price>5</price>
            </addition>
        </extra_desc>
        <portion>150</portion>
        <price>70</price>
    </Breakfast>
    <Breakfast id="2">
        <img>images/dishes/dish3_2.jpg</img>
        <name>Омлет</name>
        <description></description>
        <portion>100</portion>
        <price>100</price>
    </Breakfast>
    <Breakfast id="3">
        <img>images/dishes/dish3_3.jpg</img>
        <name>Блинчики с мясом</name>
        <description>Жареные блинчики с мясом</description>
        <portion>150</portion>
        <price>125</price>
    </Breakfast>
</menu>
